# CHANGE THE NETWORK-ID-TO-JOIN
version: '3'

services:
  zerotier:
    image: ubuntu-20.04:zerotier
    hostname: zerotier-docker
    container_name: zerotier
    restart: unless-stopped
    environment:
      - "ZEROTIER=NETWORK-ID-TO-JOIN"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    network_mode: host
    command: bash -c "$${ZEROTIER}"
